### ISSUE TITLE
Non traitement des messages ?

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#10]
Ce la fait déjà 2 fois que le bot se bloque lors de la connexion au World, je n'arrive pas à diagnostiquer son état mais il doit surement être en état stoppé.

Un problème de concurrence surement à régler rapidement

**Comment by Torf** [comment]
Étonnant, je me suis connecté plusieurs fois sur plusieurs comptes sans aucun problème.
Mais ça m'ai déjà arrivé de le voir bloqué auparavant. Le plus souvent c'est quand la connexion n'est pas top, il y a un problème de synchronisation des messages lorsque la "Connexion rapide" est cochée.
J'avais déjà eu le problème sur mes bots perso, mais qui ne me gênait pas avec ma connexion.
Si je me rapelle bien, c'est le serveur qui n'envoi pas le "AuthentificationTicketMessageAccepted" (et qui n'envoi plus rien d'ailleurs).

**Comment by Timorem** [comment]
Il faudrait faire des tests en simulant des lags ou ce genre de chose et trouver un moyen de faire un diagnostic du bot lorsque ça arrive.

**Comment by Torf** [comment]
Oui enfin toi tu as pas besoin de les simuler apparemment :p
J'essayerais en tout cas ;)

**Comment by Torf** [comment]
Peut être un problème de connexion au serveur / réception côté serveur.
Il faudrait intégrer un système qui retente connnexion + envoi du ticket au gameserver au bout d'un timeout peut être ?

**Comment by Torf** [comment]
J'ai analysé un peu ça hier mais quelque chose me tracasse : BiM attend le helloGame pour envoyer le ticket alors qu'il ne semble que le client envoi le ticket des la connexion au GameServer ? 
J'ai tenté de remédier ça mais je n'ai pas encore compris toute la structure du MITM ..

Sinon au niveau du dispatcher, je trouve que ça serais intéressant que les dispatches ne génèrent pas d'erreur bloquante (ex: je m'en fiche de l'API combat qui est en cours mais celle ci bug si je lance un combat et plante le bot) de plus, je pense qu'un plugin qui plante ne devrait pas planter le bot. Qu'envisage tu sur ce point ?

**Comment by Timorem** [comment]
Je me base sur Stump pour tout ce qui est envois/réception de messages. 
Quand un client se connecte à Stump, il envoie directement HelloGameMessage et ProtocolRequiered. Ensuite Stump attend de recevoir le ticket AuthenticationTicketMessage. 
Ici le bot attend que le client se connecte au bot et lui envoie les deux messages normalement envoyés par le serveur, le client envoie alors le ticket que le bot intercepte pour récupérer l'instance Bot. A partir de ce moment là le bot se connecte au serveur, le bot reçois alors les deux messages précédents et les stoppent de manière à ce que le client ne les reçoivent pas (une deuxième fois), et le bot envois le ticket comme l'attend le serveur.

A partir de ce moment là tout est normal et le bot ne fait office que de proxy entre le client et le serveur.

J'ai l'impression que le problème réside dans le fait que le client n'envois pas le ticket lorsque le bot le demande, peut être effectivement il faudrait renvoyer le messages ?

En ce qui concerne les erreurs c'est vraiment un point essentiel que je n'ai pas eu le temps de traiter. L'idée est que dès que le bot est susceptible d'enrayer la mécanique entre le client et le serveur (donc risque de ban?) il faut l'arrêter. Imagine le plugin de combat obtient une erreur lors de l'handle d'un message qui actualise le déplacement d'une entité et qu'ensuite le bot essaye de se déplacer à travers. 
Si le bot déconnecte le client et qu'un autre plugin a pour fonction de relancer le client a chaque fois qu'il se déconnecte, alors ça ne devrait pas poser de soucis de déconnecter le client a la moindre erreur, le bot continuerai de fonctionner (à moins que l'erreur soit récurrente, là le bot tournerait en rond et ce serait aussi problématique)

Dans tous les cas ce qu'il faut faire c'est au minimum log tous les comportements anormaux. Je ne me suis pas véritablement fixé sur si il faut throw une Exception ou pas.

**Comment by Timorem** [comment]
Fixed
