### ISSUE TITLE
Organisation de l'UI ?

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#11]
Je commencer à plancher sur la structure de l'UI.

Voici ma première idée:
- une fenêtre MDI principale
- à chaque nouvel instance Bot, une fenêtre est créer dont le parent est la fenêtre MDI. Possibilité aux plugins de fournir un FrameworkElement qui sera ajouté dans un onglet nouveau dans la fenêtre du bot -> un onglet par bot
- les plugins ont un total contrôle sur l'UI, c'est à dire ils peuvent ajouter des fenêtres comme il le désire (risque de conflit ?)

Est-ce que la structure "fenêtre MDI et 1 onglet par plugin" est viable ?
D'autres idées ?

EDIT : Quand je parle de MDI je pense tout de suite au MDI style WinForms.
Mais il est aussi possible d'intégrer un MDI de ce style : http://avalondock.codeplex.com/

**Comment by vendethiel** [comment]
Un menu pour gérer accounts (/ settings), et un système de tabs pour chaque perso co (avec des tabs dedans s'il faut) ?

**Comment by miniteck27140** [comment]
Je pencherais plus vers la personnalisation de L'UI,
Je m'explique, Une Fenêtre MDI principale, Une fenêtre Console ou toute les Log sont afficher (Toute les erreur, les packet envoyer bref les log),
Lors de la connexion au jeux, cela ouvre une nouvelle fenêtre dans lequel on affiche les plugin Activé ou non, on affiche aussi les personnage de connecter.
Personnellement je vais tenter de faire une fenêtre qui affiche la Map (j'ai bien dit tenter).

**Comment by Timorem** [comment]
@miniteck : C'est ce dont à quoi je pensais oui

@Nami-Doc : Oui ça ça va de soit.
Après j'ai pensé à quelque chose plus orientés sur des tabs sur le coté. La question qu'il faut se poser après c'est soit des fenêtres plus petites avec un container MDI du style WForms dans ce cas on pourrait avoir 2 fenêtres cote à cote pour par exemple voir le fonctionnement de 2 bots en simultanés. Ou alors avoir un système de tab où le control d'un bot prendrait toute la fenêtre principale, dans ce cas les controles ont plus d'espaces mais on pourrait pas en mettre 2 côte à côte.

**Comment by vendethiel** [comment]
Des tabs horizontales pour les accounts (pour le texte), et des tabs verticales avec des icones pour les différents trucs ? Et oui 1 bot prend tout l'écran

**Comment by miniteck27140** [comment]
Il serais aussi bien c'est de faire un système de création de fenêtre et personnalisation de fenêtre via les Plug-in.
Cela permet d'avoir une liberté de création.

**Comment by vendethiel** [comment]
Une création de tabs verticales, oui.

**Comment by Timorem** [comment]
Oui voilà j'ai pensé à ça. Après une disposition style Visual Studio est sympa aussi mais vu que c'est un truc tu settup et tu lances je pense que c'est pas adapté.

**Comment by Timorem** [comment]
Voici en gros l'idée :

![UI](http://img15.hostingpics.net/pics/179125UI1.png)

L'autre choix c'est des fenêtres emboîtés dans la fenêtre principale

**Comment by miniteck27140** [comment]
Ouai celle ci pourrais être pas mal comme idée.

**Comment by Torf** [comment]
Pas mal, je prefère MDI personnellement. On peut mettre la fenêtre de la taille qu'on veut et autant de fenêtre que l'on veut !

**Comment by vendethiel** [comment]
Les persos en horizontal & les images pour les features en vertical ?

**Comment by Timorem** [comment]
Oui peu importe.
Je vais voir ce que ça donne en disposition MDI

**Comment by vendethiel** [comment]
Btw un label "question" c'est pour les questions sur le code, le fonctionnement, pas les improvements.

**Comment by Timorem** [comment]
Mieux ? :p

**Comment by Timorem** [comment]
Voilà ce que ça donnerait avec un controle MDI

![MDI](http://img15.hostingpics.net/pics/877571UI2.png)

**Comment by miniteck27140** [comment]
Personnellement j'aime moins de cette façon je préfère l'autre façon
N 'aurai tu pas oublier une Lib ou quelque chose de ce genre ? Car je peux pas ouvrir la fenêtre sans réglés les erreur.

**Comment by kesslerdev** [comment]
cela revient au même que la solution via tab on peut faire via le menu des préférences de maximiser les forms a leur ouverture ce qui reviendrai au même qu'avec les tabs(quasiment)

**Comment by Timorem** [comment]
@miniteck27140 : Quelle erreur ?
@kesslerdev : Mais au niveau du code c'est différent ^^

**Comment by miniteck27140** [comment]
En faite il suffit d'ajoutée cette référence : WPF.MDI.dll
Le lien je ne les pas sous les yeux.

**Comment by Timorem** [comment]
Tu pourrais être plus précis ?

**Comment by miniteck27140** [comment]
En faite j'avait des erreur du style que mdi:MdiContainer n'existait pas, après un re téléchargement cela refonctionne. Pas besoin de remettre de DLL.

**Comment by Timorem** [comment]
Très étrange car le namespace mdi réfère normalement au namespace de BiM.Host

**Comment by Torf** [comment]
Personnellement le mdi fonctionne bien

**Comment by Timorem** [comment]
Finalement je vais utiliser AvalonDock pour faire office de MDI c'est beaucoup plus flexible et beaucoup plus beau ^^
Au niveau de l'architecture je vais la revoir pour avoir un pattern MVVM, plus facile à manier pour bien séparer UI et Models (les bots)
