### ISSUE TITLE
Un designer ?

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#13]
Je cherche un graphiste ou un designer pour faire un design sympa d'UI car je suis vraiment mauvais là dedans.
Si vous ne manier pas WPF ce n'est pas grave j'ai juste besoin d'un psd avec les couleurs etc.

**Comment by Torf** [comment]
Je pense que pour faire une UI sympa, il faut définir - si ça n'a pas été fait - les informations qui seront affichées sur l'UI. Désolé mais moi aussi je suis mauvais là dedans. :/

**Comment by Timorem** [comment]
Je parle pas de la disposition de l'UI forcément mais déjà un theme ?

**Comment by Torf** [comment]
Je pense que pour un graphiste, ce n'est pas simple d'imaginer un thème sans avoir une idée globale de l'UI finale.
Après tu as peut être déjà en tête des ébauches de l'UI ? Personnellement, même en ayant déjà vu d'autres bots MITM, je n'arrive pas à imaginer comment il pourrait être (pour être parfait bien sur _-_).

**Comment by Torf** [comment]
Sinon tu peux - peut-être - arriver à faire quelque chose de sympa juste en utilisant des thèmes WPF ?
Il y en a des sympas.

**Comment by Timorem** [comment]
Le truc déjà c'est que les fenêtres MDI sont entièrement conçu depuis du XAML (bords compris), donc faut tout réécrire pour que ce soit cohérent.
Ensuite j'ai une ébauche en tête déjà mais de base il n'y a pas beaucoup de contrôles, juste des trucs informatifs, c'est vraiment les plugins qui font tout.
Après on peut être un peu "foufou" et faire vraiment un truc nouveau, mais là j'ai pas d'idée ^^
