### ISSUE TITLE
Choix du serveur impossible

### ISSUE THREAD

**Issue by miniteck27140** [Emudofus/BehaviorIsManaged#14]
Salut tout le monde,
Je vous poste un petit problème qui m'est survenue lors de la connexion au serveur.
Alors je m'explique, je me connecte sur Dof. arrivé au choix du serveur, le bot reste bloqué donc impossible de continué dans le jeux.
Je vous montre les log : 
http://pastebin.fr/24483
Voila je vous laisse regarder.

**Comment by Timorem** [comment]
Tu as bien la dernière version ?

**Comment by miniteck27140** [comment]
Oui j'ai bien la dernière version

**Comment by Timorem** [comment]
Go skype (bouh2a)

**Comment by Seth-** [comment]
Salut a vous,
d'abords bravo à toi pour ce magnifique projet, j’espère qu'il ira loin! :)
J'ai aussi ce problème pour faire le corriger je rajoute simplement : "client.Bot.SendToServer(new AuthenticationTicketMessage("fr", message.ticket));"
Apres la ligne "logger.Debug("Bot retrieved with ticket {0}", message.ticket);"
Et je supprime la fonction : 

[MessageHandler(typeof(HelloGameMessage), FromFilter = ListenerEntry.Server)]
        private void HandleHelloGameMessage(Bot bot, HelloGameMessage message)

(Ne me demande pas pourquoi sa marche, je n'en n'ai strictement aucune idée, j'ai simplement analysé l'ordre des packets et envoyé l'AuthenticationTicketMessage avant)

Je compte m'investir dans ce projet durant les vacances et lorsque que j'ai pas trop de boulot :)

**Comment by Timorem** [comment]
Hm intéressant, le truc c'est que moi j'ai encore pas eu ce bug.
Normalement le bot envois AuthenticationTicketMessage lorsque le serveur lui envois HelloGameMessage. Par contre il faut bien empêcher l'envois de HelloGameMessage sinon le serveur le reçois 2 fois et c'est louche.

Tu es bien sûr que c'est ça qui résous le problème ?

**Comment by Seth-** [comment]
Aucun problème de connexion avec ce système, alors que sa ne marche pas avec l'autre :/

Sinon j'ai trouvé 2 petit problème (Je pense pas que ce soit utile d'ouvrir deux nouveaux posts pour ça :p ) :
- Pas mal de NullReferenceException quand on lance un combat ou un défi
- m_nonSharedHandlers est vide pourtant le plugin WelcomeMessageRegister marche mais UnSharedHandlerTest ne marche pas (Je t'avoue que je comprend pas là X_x )

Je suis désolé de ne pouvoir que traquer les bugs et ne pas les corriger mais je manque de temps pour comprendre vraiment toute l'architecture et faire des petites modifs

**Comment by Timorem** [comment]
Les combats c'est normal je n'ai pas fini de les implanter.
Le deuxième bug est étrange effectivement, je vais voir si je peux le catch.

Je suis en train de rédiger quelques lignes sur l'architecture pour expliquer mes choix etc.

**Comment by Seth-** [comment]
Super ! En tout cas si je peux faire quoi que ce soit de pas trop long pour toi, n'hésite pas a me demander :)

**Comment by Timorem** [comment]
Le deuxième bug était évident, j'ai laissé le handler en static donc forcément ça fonctionne. Et les constructeurs statics ne sont jamais appelés car il n'y a pas de référence à ces classes, faut que je trouver une alternative ...
