### ISSUE TITLE
Reconnexion en combat

### ISSUE THREAD

**Issue by xiwiz** [Emudofus/BehaviorIsManaged#17]
Salut !

La reconnexion en combat ne fonctionne pas. J'imagine qu'elle n'est pas encore gérée..
Mais si ça peut t'aider, voici le log : 

[11:15:23](Bot #10) Fatal : System.Exception: Cannot dispatch GameFightSynchronizeMessage ---> System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
Nom du paramètre : index
   à System.Collections.Generic.List`1.get_Item(Int32 index)
   à BiM.Behaviors.Game.Actors.Fighters.MonsterFighter.Update(GameFightMonsterInformations msg) dans BehaviorIsManaged\trunk\Behaviors\Game\Actors\Fighters\MonsterFighter.cs:ligne 68
   à BiM.Behaviors.Game.Actors.Fighters.MonsterFighter.Update(GameFightFighterInformations informations) dans BehaviorIsManaged\trunk\Behaviors\Game\Actors\Fighters\MonsterFighter.cs:ligne 77
   à BiM.Behaviors.Game.Fights.Fight.Update(GameFightSynchronizeMessage msg) dans BehaviorIsManaged\trunk\Behaviors\Game\Fights\Fight.cs:ligne 419
   à BiM.Behaviors.Handlers.Context.FightHandler.HandleGameFightSynchronizeMessage(Bot bot, GameFightSynchronizeMessage message) dans BehaviorIsManaged\trunk\Behaviors\Handlers\Context\FightHandler.cs:ligne 100
   à BiM.MITM.Network.NetworkMessageDispatcher.InternalDispatch(NetworkMessage message, Object token) dans BehaviorIsManaged\trunk\MITM\Network\NetworkMessageDispatcher.cs:ligne 93
   à BiM.MITM.Network.NetworkMessageDispatcher.Dispatch(NetworkMessage message, Object token) dans BehaviorIsManaged\trunk\MITM\Network\NetworkMessageDispatcher.cs:ligne 53
   --- Fin de la trace de la pile d'exception interne ---
   à BiM.MITM.Network.NetworkMessageDispatcher.Dispatch(NetworkMessage message, Object token) dans BehaviorIsManaged\trunk\MITM\Network\NetworkMessageDispatcher.cs:ligne 73
   à BiM.MITM.Network.NetworkMessageDispatcher.Dispatch(Message message, Object token) dans BehaviorIsManaged\trunk\MITM\Network\NetworkMessageDispatcher.cs:ligne 40
   à BiM.Core.Messages.MessageDispatcher.ProcessDispatching(Object processor) dans BehaviorIsManaged\trunk\Core\Messages\MessageDispatcher.cs:ligne 475
   à BiM.Behaviors.Bot.OnTick() dans E:\Projets\BehaviorIsManaged\trunk\Behaviors\Bot.cs:ligne 140

**Comment by Timorem** [comment]
Je travaille dessus :)

**Comment by Timorem** [comment]
Fixed
