### ISSUE TITLE
Fix the pathfinder

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#2]
The pathfinder is correct but doesn't give the same path as the client, so it's a possible source of ban

http://postimage.org/image/o6b7bpz4d/

**Comment by kesslerdev** [comment]
pourquoi ne pas prendre le même algorithme que le client?

**Comment by vendethiel** [comment]
Parce qu'il est dégueulasse au possible, entre autres

**Comment by kesslerdev** [comment]
Autant pour moi je n'avais pas regardé les sources du pathfinder et c'est vrai que c'est pas terrible

**Comment by Timorem** [comment]
Il faut le comprendre pas le copier

**Comment by vendethiel** [comment]
c'est bien c'que j'dis ouais, faut essayer de comprendre pourquoi c'est autant de la merde

**Comment by vendethiel** [comment]
Tu peux mettre "fix #2" (fix fixes close closes ...)
