### ISSUE TITLE
Authentification:CharactersListEntry not implemented

### ISSUE THREAD

**Issue by xiwiz** [Emudofus/BehaviorIsManaged#20]
Salut,

Je viens de pull ton dernier commit (Ajout de selection/suppression/creation de character) et j'ai une exception lors de la sélection du personnage.
Dans CharacterSelectionView.xaml, Authentification:CharactersListEntry n'est pas implémenté.
Voici la trace :

System.Windows.Markup.XamlParseException occurred
  Message=La méthode ou l'opération n'est pas implémentée.
  Source=PresentationFramework
  LineNumber=26
  LinePosition=10
  StackTrace:
       à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
       à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
       à BasicPlugin.CharacterSelection.CharacterSelectionView.InitializeComponent()
       à BasicPlugin.CharacterSelection.CharacterSelectionView..ctor()
  InnerException: System.NotImplementedException
       Message=La méthode ou l'opération n'est pas implémentée.
       Source=PresentationFramework
       StackTrace:
            à System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
            à System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
            à System.Windows.Baml2006.Baml2006Reader.Process_PropertyTypeReference()
            à System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
            à System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
            à System.Windows.Baml2006.Baml2006Reader.Read()
            à System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
            à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       InnerException:

**Comment by Timorem** [comment]
Tu as bien rebuild toute la solution, tu n'as pas d'erreur de compil ?

**Comment by xiwiz** [comment]
Oui, j'ai rebuild la solution et j'ai n'ai pas d'erreurs...
Sauf au lancement, je ne pense pas que ça soit lié mais j'ai :

[13:33:49] Plugin 'Basic Plugin' loaded
[13:33:49](PluginManager #10) Error : Plugin BiM.Behaviors has no IPlugin entry point
[13:33:49](PluginManager #10) Error : Plugin BiM.Core has no IPlugin entry point
[13:33:49](PluginManager #10) Error : Plugin BiM.MITM has no IPlugin entry point
[13:33:49](PluginManager #10) Error : Plugin BiM.Protocol has no IPlugin entry point
[13:33:49] Plugin 'Fight Plugin' loaded
[13:33:49](PluginManager #10) Error : Plugin NLog has no IPlugin entry point
[13:33:49] Plugin 'Simple Plugin' loaded
[13:33:49](PluginManager #10) Error : Plugin System.Windows.Interactivity has no IPlugin entry point
[13:33:49] Plugin 'Window Manager' loaded
[13:33:49](PluginManager #10) Error : Plugin zlib.net has no IPlugin entry point
[13:33:49] MITM started

**Comment by Timorem** [comment]
Non ce n'est pas lié, mais tu peux déjà définir la propriété 'Copy Local' des références à False. Tu as bien tous les fichiers, notamment CharactersListEntry dans BiM.Behaviors.Authentifcation ?

**Comment by xiwiz** [comment]
Oui, j'ai bien le fichier CharactersListEntry.cs
De quelle propriété tu parles ?

**Comment by Torf** [comment]
Il parle du problème de IPlugin qui n'est pas grave.
Sinon essaye de supprimer ton dossier et de recloner avec GitHub, car ça
fonctionne plutôt bien pour nous.

**Comment by Timorem** [comment]
Si tu peux me contacter sur skype je pourrais résoudre le problème ;)

**Comment by xiwiz** [comment]
Fixed.
