### ISSUE TITLE
[AutoFight] ContextActor.NotifyStartMoving : Actor start cell incorrect for this moving path Position=505, StartPath=478

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#22]
This kind of message comes quite often. Also, sometimes my character simply never reaches the monster : it always comes on the cell adjacent to the monster, and move again only once the monster moves...

**Comment by vendethiel** [comment]
The bot can't handle 1cell moves for some reason

**Comment by Timorem** [comment]
In fact the client don't even care about a movement that begins on a different cell from the actor. So I can remove this message, it doesn't have an impact but that's strange I know.

**Comment by FastFrench** [comment]
I'm sorry, but I do not agree here. 

Outside fights, each time a group moves , we got the error message like : ContextActor.NotifyStartMoving : Actor start cell incorrect for this moving path Position=249, StartPath=303, Path=303,317,330,344
As you can see here, it's not only for 1 cell movements, and the actor really moves on the client display. 

It seems that we do not update actor's position when handling GameMapMovementMessage. I guess that's the reason of the warning. If you carefully watch the successiv GameMapMovementMessage messages for the same actor, they are coherent (starting point = ending point of the previous), but we still have the warning. 
We handle the StopMoving in the fights and for played characters, but not for actors on the map outside fights. That's surely the reason of : 
- the warning (origin of this issue)
- an problem seen in AutoFight, where the character never reaches the groupe. 

To make it clear, for movement of monsters on the map (outside fights), we only receive the GameMapMovementMessage. So we have to update the position of non-played actors based on this only message.
