### ISSUE TITLE
[AutoFight] FightTeam.Update : Cannot set the leader because fighter -3 is not in team

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#23]
This error comes also quite often. It's not related with invocs : I'm playing a lv 9 cra, so no invoc here.

**Comment by Timorem** [comment]
That's is strange, I would need the packets log.

**Comment by FastFrench** [comment]
I've not found a way to easily extract a small and significative part of the log of messages (as they are not timestamped). I will try harder next time ;)

**Comment by Timorem** [comment]
I will implement this feature

**Comment by Timorem** [comment]
Fixed
