### ISSUE TITLE
[AutoFight] End of fight

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#24]
The summary window at the end of the fight remains on the screen, so /sit order is not processed and the bot is stuck. No idea how to remove this screen in a clean way, as it seems that no message is triggered when we manually remove it by pushing the button. 
[Edit] : 1/ anyway /sit doesn't work even when this window is closed. 
           2/ A dirty way to close this "end of fight" window would be to send proper keys to the client. Any idea of a better way to do it ?

**Comment by Timorem** [comment]
There is actually a plugin 'WindowManager' that should close all windows opened (levelup, end fight ...) but the probleme is it uses Windows Messages, and send directly a message to the dofus window handle. But it required admin privileges to allow this, so it's not a good way.
Maybe we can send a network message that will close the window ?

**Comment by FastFrench** [comment]
What do you mean with "Network message" ? I've seen no message between the client and the server when we close the Window. And on old MiM Bots, the fact you triggers other actions (through messages) finally closes the Window. Not sure if it's still the case. But that's for sure an important point to solve here.

**Comment by Timorem** [comment]
This is what I meant, find a message for an other action that closes the window.

**Comment by FastFrench** [comment]
Unfortunately an emote (like sitting) is not enough. But starting another fight do the trick.
