### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Shravan1804** [Emudofus/BehaviorIsManaged#33]
Hi guys,

I would like to participate in this project not only from the plugin side but also with the core development. I think it will be a good way to better my C# skills and also be a nice start with open source development.
So I read all the wiki - readme and I started reading through the code but man, it is more huge than I thought! I am in fact completely lost between all these files. This brings me to my request/question :)

I would like to ask if someone could explain the flow of the application from its start. I don't ask to write a full document (this could be one of my first contribution once I understood everything myself) but simply some key facts which could help me browse through the code and understand what is really happening.
For example it could be:
1) app start loading file X, Y and Z.
2) start MiTM behavior using class U, V
3) connect to server using class M, N
4) identifications using class Q, W
5) loading the plugins, class R, T
.
.
.
n) ...

I am sure this won't take so much time for someone who worked on the project for months already compared to the time that will be needed for any random guy trying to really get into it.
I think this could also help any other potential future developers :).

You can answer me in English as well as in French, I don't mind.

Thanks a lot,

Shravan

**Comment by vendethiel** [comment]
true, improving the wiki would be a good start

also, it may take quite some time for you to understand, but at least you'd understand how the bot was designed.

**Comment by Timorem** [comment]
The problem is that I don't have the time to make a full documentation but I can help you to understand the logic of the program.
I invite you to come on the IRC channel so we can speak easily

**Comment by Shravan1804** [comment]
Ok, but I think it will take you as much time discussing it than writing quickly the big lines here ;)
Anyway, when do you prefer to meet on irc? It is better for me in the evenings from 18h.

**Comment by Timorem** [comment]
There is so much to explain to do it now anyways. Wednesday I'll have some time to explain you everything you want ;)

**Comment by Shravan1804** [comment]
Thanks, I look forward to it.
