### ISSUE TITLE
Several bots running at same time

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#37]
It looks like the first bot receives the proper messages. The second bot, the messages of 1st and 2nd bot. And the 3rd, the messages of bot 1, 2 and 3. 

To make it simple, we can say it doesn't work well with several bots. 

Also, for a single bot, starting and stopping the plugin works well. But when I have several bots active, the plugin remains active no matter how many times I try to stop it.

**Comment by Timorem** [comment]
I have no trouble with it

**Comment by FastFrench** [comment]
Seems better now, but not sure what was the problem
