### ISSUE TITLE
Erreur choix du personnage

### ISSUE THREAD

**Issue by miniteck27140** [Emudofus/BehaviorIsManaged#4]
Bonjour Bouh2,
Je te poste une erreur que j'ai détecter. Je te la montre si sa peut t'aider.
<img src="http://nsa29.casimages.com/img/2012/08/14//120814045022450648.png" border="0"/>

Voila Bonne chance pour la suite.

**Comment by volgar1x** [comment]
#6

j'ai corrigé ça, bouh2 doit confirmer mais pour ma part ça marche comme il se doit

**Comment by vendethiel** [comment]
@Blackrush Utilise "#6" ;)

**Comment by Timorem** [comment]
Etrange comme erreur, l'entrée n'existe pas dans le d2o il y a une raison.

**Comment by miniteck27140** [comment]
Je n'est pas toucher au code sources par peur de faire une erreur donc j'ai tester avec se que Blackrush à passer cela fonctionne Bizarre.

**Comment by Timorem** [comment]
Oui il a juste supprimé l'erreur est défini le spell à null. Ca ne résout rien du tout.

**Comment by volgar1x** [comment]
L'erreur empêchait de se connecter et provenait du chargement des .d2o, il manque le niveau 6 d'un sort ;)

**Comment by Timorem** [comment]
Oui la question est pourquoi, on n'ignore pas une erreur comme ça, soit c'est un manque dans les d2o donc ça vient du client, dans ce cas on doit effectivement ignorer l'erreur (mais ça m'étonnerait sinon ça planterait aussi au niveau du client) ou alors il y a une erreur lorsqu'il lit le d2o donc il retourne null
