### ISSUE TITLE
Redis not working

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#40]
RedisServerHost.Instance.StartOrFindProcess(); is blocking forever (well, over 5 minutes). Even if I start redis-server.exe manually. 
redis-cli.exe and redis-benchmark.exe work fine. 

(Could not load file or assembly ServiceStack.Redis Version 3.9.29.0)

It works in x86 mode.

**Comment by Timorem** [comment]
Hm, is the assembly correctly built ? Any warning, like incoherences in assembly architecture target ?

**Comment by FastFrench** [comment]
I guess there was no warning on a Reduild all. Just the (hidden) exception.

Maybe it's related to the fact I've made some minor changes to remove the warnings in Redis.

**Comment by FastFrench** [comment]
A way to make it work : build in x86 mode
