### ISSUE TITLE
Aide!

### ISSUE THREAD

**Issue by ludovikallen** [Emudofus/BehaviorIsManaged#46]
quelqu'un pourrais m'aider je ne suis pas capable d'ouvrir le programme est-ce que quel'un pourrais me dire ou trouver le programme dans les dossiers ou me rediriger vers un tuto merci a l'avance

**Comment by vendethiel** [comment]
Non.

**Comment by ludovikallen** [comment]
mais ou aller pour pouvoir l'ouvrir

**Comment by vendethiel** [comment]
Si c'que tu cherches c'est un truc qui puisse jouer à ta place c'est pas la peine actuellement, c'est en phase de dev

**Comment by ludovikallen** [comment]
la est ce que sa marche ?

**Comment by ludovikallen** [comment]
il excite aucun tuto ?
