### ISSUE TITLE
Config Initiale

### ISSUE THREAD

**Issue by Jean22** [Emudofus/BehaviorIsManaged#47]
Bonsoir,

Tout d'abord, une bonne année 2013 à tous :)
J'ai découvert BIM il y a deux-trois semaines; merci aux devs ! J'aimerais maintenant essayer de le faire tourner et d'utiliser le plugin sniffer qui est déjà codé avant de me lancer dans le développement de mes propres plugins.
Dans mon visual studio, j'ai "build" toutes les assembly sans problèmes; tous les voyants sont aux verts. Par contre je suis perdu quand j'essaie de lancer l'application. J'ai essayé de lancer tous les .exe créés dans certains ordres logiques mais sans succès. Si j'essaie de le lancer via Visual Studio, celui ci refuse.
Pouvez vous donc m'indiquer comment je peux faire fonctionner tout ça?

Merci d'avance,

Jean22

**Comment by vendethiel** [comment]
Host.exe

**Comment by Jean22** [comment]
Merci pour ta réponse.
J'ai bien sûr lancé Host.exe. Ce qu'il se passe ensuite, c'est qu'il bloque avec ce dernier message dans le log : "Starting redis server ". Ensuite, rien, aucun boutons. Je lance D., aucune réaction.

**Comment by Timorem** [comment]
Veille a ce que les projets soient lancés en mode x86

**Comment by Jean22** [comment]
Merci pour la réponse.
Je suis allé dans build - configuration manager et j'ai changé le menu déroulant "active solution platform" sur "x86" (il était avant sur "mixed platform"). Je build ensuite le tout avec succès ("Build: 17 succeeded or up-to-date, 0 failed, 0 skipped").
Mais cela ne change rien. Après avoir lancé le Host.exe, je reste bloqué au même endroit avec ce message dans le log "Starting redis server ". Aucune réaction si D. est lancé.
Merci d'avance.

**Comment by Timorem** [comment]
Va dans Configuration Manager et veille à cet que tous les champs Platform soient sur x86

**Comment by Jean22** [comment]
C'est le cas...

**Comment by Shravan1804** [comment]
Salut et bonne année à tous,

Juste une idée comme ça: est ce que la path de ton dossier D. (vérifie le lien du shortcut de D.) est bien dans program files ou program files x86?
Dans le cas contraire, il faut que tu ailles modifier le code de la fonction GetDofusPath dans Host.cs.
Par exemple dans mon cas (le dossier se trouve en C:\Hry\Dofus2), j'ai rajouté avant l'accolade fermante du dernier else de la fonction le code suivant:

<code>
else if (Directory.Exists("C:\\Hry\\Dofus2"))
                        m_dofusPath = "C:\\Hry\\Dofus2";
</code>

Corrige moi Timorem s'il y a une manière plus élégante de procéder :)

Shravan

EDIT: lol les \ ne sont pas échappés oO, même sans les balises code. J'ai du mettre 3x \ pour que sa s'affiche correctement :p

**Comment by Jean22** [comment]
Merci pour vos réponse. En n'ayant rien fait de particulier (peut être le redémarrage de l'ordinateur?), ce matin le programme ne bloque plus sur "Starting redis server ..." :)
Maintenant il continue jusqu'à "MITM started". Il dit bien que les plugins sont loaded mais après je n'ai plus de réaction. Je lance D. sans que rien d'autre ne se passe (idem si j'inverse l'ordre et lance D. en premier). Il n'y a pas de boutons à part ceux pour le logs.
Que dois je faire une fois arrivé à cette étape?

Merci d'avance.

**Comment by Jean22** [comment]
Encore un changement... Ce matin contrairement à hier, host.exe rebloque au même endroit:
<log>
...
[09:51:52] File added : Url.d2o
[09:51:52] File added : WorldMaps.d2o
[09:51:52] Starting redis server ...
</log>

Alors je lance d'abord redis-server.exe avant host.exe et là sa se débloque et j'arrive à ce niveau pour le log:
<log>
...
[09:54:28] Starting redis server ...
[09:54:28] Loading ./maps.dat...
[09:54:28] Loading maps positions ...
[09:54:28] Loading submaps ...
[09:54:29] MITM started
</log>

La toute première fois que ça a fonctionné, il y avait beaucoup plus de détails dans le logs sur les maps (140 MB en tout) qu'il chargeait en gris clair mais maintenant cela n'apparaît plus (une histoire de cache?).
Quelqu'un a une idée sur comment je peux régler le problème?

Merci d'avance.

**Comment by FastFrench** [comment]
Pour les maps, c'est normal : il charge les maps dans la base de données la première fois. Ensuite c'est plus rapide. 
Si tu supprimes le fichier map.dat (?), le traitement complet devrait se reproduire. 

Pour ton blocage, as-tu modifié l'IP dans ton fichier de config Dofus ? Il faut lui dire que l'IP du serveur est ta propre machines.

Pour l'ordre, il faut lancer host.exe en premier, puis te connecter avec le client. Si ton fichier de config Dofus est correct, tu ne peux plus te connecter avec le client Dofus quand BiM n'est pas lancé.

**Comment by Jean22** [comment]
Merci pour ta réponse!
Je change l'ip du server pour localhost soit 127.0.0.1 n'est ce pas?
Je vais chercher le fichier de config de D. maintenant. Peut être peux tu me guider vite fait? Est ce un xml? Connais tu le nom du fichier?

**Comment by Timorem** [comment]
config.xml dans le dossier app qui est le dossier racine de l'executable

**Comment by Jean22** [comment]
Merci à chacun pour votre aide, tout fonctionne maintenant.
Juste pour comprendre, si host.exe s'arrêtait à "Starting redis server ..." c'était dû au fait que le config.xml de D. n'était pas correctement modifié?
Merci encore,

Jean22

**Comment by Timorem** [comment]
Nan apparemment il n'arrive pas à lancer le processus, il faudrait trouver pourquoi

**Comment by Jean22** [comment]
Ok merci :)
Vous pouvez fermer l'issue.
