### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cedric95** [Emudofus/BehaviorIsManaged#50]
Bonjour à tous! 
Je suis BiM depuis quelques mois.
Mais aujourd'hui je suis vraiment à la recherche d'un bot pour Dofus!
Alors je voudrais savoir, quand serait disponible un .exe pour le bot, même si tout n'est pas encore fini. J'aimerais le tester!

Voila ! Merci à tous ;)

**Comment by vendethiel** [comment]
compile-le

**Comment by cedric95** [comment]
Coucou, merci de ta réponse! Je vais essayer de le compiler ;)

A bientôt!

**Comment by vendethiel** [comment]
puis lance Host.exe

**Comment by cedric95** [comment]
Je n'ai pas réussi à le compiler avec Microsoft Virtual Studio, il m'a mis pleins d'erreur... Je ressaye demain!

**Comment by cedric95** [comment]
Erreur  2   'BiM.Behaviors.Profiles.Actions.MoveAction.OnStart()' : ne peut pas changer les modificateurs d'accès en cas de substitution du membre hérité 'BiM.Behaviors.Profiles.ProfileAction.OnStart()' de 'protected'   C:\Users\Cedric\Desktop\TestResults\Behaviors\Profiles\Actions\MoveAction.cs    29  30  BiM.Behaviors
Erreur  4   Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\MITM\CSC    BiM.MITM
Erreur  6   Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Host\CSC    BiM.Host
Erreur  7   Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Host\CSC    BiM.Host
Erreur  8   Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Plugins\SimplePlugin\CSC    SimplePlugin
Erreur  9   Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Host\bin\Debug\BiM.Host.exe' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\SimplePlugin\CSC    SimplePlugin
Erreur  10  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\SimplePlugin\CSC    SimplePlugin
Erreur  11  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Plugins\FightPlugin\CSC FightPlugin
Erreur  12  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Host\bin\Debug\BiM.Host.exe' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\FightPlugin\CSC FightPlugin
Erreur  13  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\FightPlugin\CSC FightPlugin
Erreur  14  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Plugins\WindowManager\CSC   WindowManager
Erreur  15  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Host\bin\Debug\BiM.Host.exe' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\WindowManager\CSC   WindowManager
Erreur  16  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\WindowManager\CSC   WindowManager
Erreur  17  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Plugins\SnifferPlugin\CSC   SnifferPlugin
Erreur  18  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Host\bin\Debug\BiM.Host.exe' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\SnifferPlugin\CSC   SnifferPlugin
Erreur  19  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\SnifferPlugin\CSC   SnifferPlugin
Erreur  20  Erreur de build inconnue, 'MC3050 : impossible de trouver le type 'BoostableStat'. Notez que les noms de type respectent la casse.'    C:\Users\Cedric\Desktop\TestResults\Plugins\BasicPlugin\CharacterInfo\CharacterInfoView.xaml    85  120 BasicPlugin
Erreur  21  Erreur de build inconnue, 'MC3074 : la balise 'BindingProxy' n'existe pas dans l'espace de noms XML 'clr-namespace:BiM.Host.UI.Helpers;assembly=BiM.Host'. Ligne 16 Position 6.'   C:\Users\Cedric\Desktop\TestResults\Plugins\BasicPlugin\CharacterSelection\CharacterSelectionView.xaml  16  6   BasicPlugin
Erreur  22  Erreur de build inconnue, 'MC3066 : la référence de type ne peut pas trouver un type public nommé 'ActiveGroupingCollectionView'. Ligne 11 Position 94.'    C:\Users\Cedric\Desktop\TestResults\Plugins\BasicPlugin\Inventory\InventoryView.xaml    11  94  BasicPlugin
Erreur  23  Erreur de build inconnue, 'MC3074 : la balise 'BindingProxy' n'existe pas dans l'espace de noms XML 'clr-namespace:BiM.Host.UI.Helpers;assembly=BiM.Host'. Ligne 15 Position 6.'   C:\Users\Cedric\Desktop\TestResults\Plugins\BasicPlugin\ServerSelection\ServerSelectionView.xaml    15  6   BasicPlugin
Erreur  24  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Behaviors\bin\Debug\BiM.Behaviors.dll' est introuvable C:\Users\Cedric\Desktop\TestResults\Plugins\FFFightPlugin\CSC   zFFFightPlugin
Erreur  25  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\Host\bin\Debug\BiM.Host.exe' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\FFFightPlugin\CSC   zFFFightPlugin
Erreur  26  Le fichier de métadonnées 'C:\Users\Cedric\Desktop\TestResults\MITM\bin\Debug\BiM.MITM.dll' est introuvable   C:\Users\Cedric\Desktop\TestResults\Plugins\FFFightPlugin\CSC   zFFFightPlugin

**Comment by Timorem** [comment]
Ah oui, je corrigerai ça

**Comment by cedric95** [comment]
Merci ;)

**Comment by cedric95** [comment]
Bonjour à tous! Désoler de vous ré-embêter ! J'ai enfin reussi de compiler avec la correction de Timorem ! Merci à toi!
Maintenant quand je lance Host.exe, il n'y a que General Logs qui apparait! Je voudrais savoir si c'est normal (voir le screen ci-dessous) . Merci! Ah oui, si j'utilise un Proxy sur Dofus, le bot utilisera la même ip que Dofus, ou mon ip local? Merci!
![bim](https://f.cloud.github.com/assets/3617352/212663/4055460e-8322-11e2-88ff-0d62c9e1d94c.png)

**Comment by Timorem** [comment]
Il faut connecter ton client dofus à l'ip du MITM (donc localhost:443)

**Comment by cedric95** [comment]
```
<!--======================================================================-->
<!--                  Constantes pour l'accès au serveur                  -->
<!--======================================================================-->


<entry key="connection.useSniffer" type="Boolean" >false</entry>
<entry key="connection.snifferHost">localhost</entry>
<entry key="connection.snifferPort" type="int">18001</entry>
<entry key="connection.host">localhost</entry>
<entry key="connection.port">443</entry>
```

C'est bien cela? ;)

**Comment by Timorem** [comment]
C'est p'tet 5555 en fait, je ne sais plus

**Comment by cedric95** [comment]
Merci, c'est bien ça ! ;)

**Comment by cedric95** [comment]
Nouveau problème:
[01:44:40] Bot started
[01:45:01](MITM #6) Error : Cannot connect to 213.248.126.180:5555.
[01:45:01] Bot stopped
[01:45:01](ClientManager`1 #6) Error : Exception occured during client connection : System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   à BiM.Core.Network.ClientManager`1.ProcessAccept(SocketAsyncEventArgs e) dans c:\Users\Cedric\Desktop\BehaviorIsManaged-master\Core\Network\ClientManager.cs:ligne 184

Quelqu'un sait ce que je dois faire?

**Comment by Torf** [comment]
L'adresse IP du serveur d'authentification a dû changer. Change la dans le config.xml de BIM : 

``` xml
<Key name="RealAuthHost">
  <string>213.248.126.40</string>
 </Key>
```
