### ISSUE TITLE
Did D change their IP for the server?

### ISSUE THREAD

**Issue by Jean22** [Emudofus/BehaviorIsManaged#55]
I tried connecting the mitm tonight but it wouldn't work and display this error:
cannot connect to 213.248.126.180...
Did Ankama change the ip to connect to their server?
I didn't make a backup of the config.xml and cannot revert to the original ip :/ So if anyone has the correct IP, I would appreciate it :)

Thanks!

**Comment by vendethiel** [comment]
[Seems like it](https://github.com/Emudofus/BehaviorIsManaged/issues/50#issuecomment-15007218).
