### ISSUE TITLE
Server closed the connection after character selection

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#57]
I just had this problem with a few characters, I have no log error the server closed the connection by itself and I don't know why ?

Does anybody had the same issue ?

**Comment by vendethiel** [comment]
-> #58

**Comment by FastFrench** [comment]
Yes, and no idea why. When it happens, I connect the character without BiM, remove the weapon (if it's not enough then remove all equipement) and move the character to another map. Then I can connect through BiM, and you can put stuff back. 
Even with exceptions active, no hint on what's wrong.
