### ISSUE TITLE
2.11.4

### ISSUE THREAD

**Issue by FastFrench** [Emudofus/BehaviorIsManaged#60]
Hello. With the new version 2.11.4 (may 8th.), my bot is not usable anymore. The clients freeze after a small and variable delay, like 1 to 10 minutes. It seems that no message have changed, neither data structures. My bot detects the client is frozen, then  kill them restart it... but it needs to restart much too often, so it's not usable. 

Do some other bots have the same problem?

**Comment by FastFrench** [comment]
Fixed. Non-MiM bots will have very hard time : now the server send new messages definition in messages. And then use it. For now it is very simple, but it looks like they will use this technic to check integrity of the Dofus client.

With this technic it would be very easy to stop MiM bots.

**Comment by scalexm** [comment]
How does it work? With RawDataMessage?

**Comment by Timorem** [comment]
They send a SWF that is dynamically executed.
Why would it be easy to stop MiM bots ? We always can intercepts this messages and modify our protocol.

**Comment by FastFrench** [comment]
We have the choice for dynamic messages : either filter and refuse to execute them => they can easily detect that. 
Or let the client handle them (I'd say BiM could simply ignore those messages, or store the content of the scripts for later analysis). Then it means that they can ask to the client simple things like...
  What is the IP of the server ?
  Did YOU send me this message ? 
  ect...

You got the point ?

But they do not really need that to stop MiM, they already have all the materials they may need. Have you checked the SequenceNumberRequestMessage/SequenceNumberMessage + BasicAckMessage ? They have enough information here to know that some messages are not send by the client. 
If they do, we may try to alter those messages to better hide ourself. 

@LittleScaraby : Yep, they're using RawDataMessage to send the swf data. Then this is handeld as any other messages, with its specific Id.
