### ISSUE TITLE
from where to strat?

### ISSUE THREAD

**Issue by yelhouti** [Emudofus/BehaviorIsManaged#67]
Hi guys I've looked a little through your code and I would like to test it but don't know how to start, I'm more used to Java and Scala and I would also be interested in participating to this big project, any help would be great thanks :)

**Comment by FastFrench** [comment]
Sorry guy, but this project is not active anymore. 

I don't even remember what Dofus looks like ;)

**Comment by vendethiel** [comment]
Sounds a bit late to reply.
